version: '3.8'

services:
  cv-app:
    image: cv-app:latest
    container_name: cv-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    networks:
      - cv-network

networks:
  cv-network:
    driver: bridge
