name: Deploy to NAS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t cv-app:latest .
          docker save cv-app:latest | gzip > cv-app.tar.gz

      - name: Copy files to NAS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USERNAME }}
          key: ${{ secrets.NAS_SSH_KEY }}
          port: ${{ secrets.NAS_PORT }}
          source: "cv-app.tar.gz,docker-compose.yml,deploy.sh"
          target: "~/docker/cv-app"

      - name: Deploy on NAS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USERNAME }}
          key: ${{ secrets.NAS_SSH_KEY }}
          port: ${{ secrets.NAS_PORT }}
          script: |
            cd ~/docker/cv-app
            chmod +x deploy.sh
            ./deploy.sh
