name: Deploy to NAS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pre-download drone-scp (before WireGuard)
        run: |
          mkdir -p /tmp/drone-scp
          cd /tmp/drone-scp
          curl -L https://github.com/appleboy/drone-scp/releases/download/v1.8.0/drone-scp-1.8.0-linux-amd64 -o drone-scp
          chmod +x drone-scp
          echo "/tmp/drone-scp" >> $GITHUB_PATH

      - name: Setup WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard resolvconf
          echo "${{ secrets.WIREGUARD_CONFIG }}" > wg0.conf
          sudo wg-quick up ./wg0.conf

      - name: Copy files to NAS via SSH
        uses: appleboy/scp-action@v1
        with:
          host: 192.168.1.22
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "app/**,components/**,data/**,lib/**,public/**,types/**,Dockerfile,docker-compose.yml,.dockerignore,next.config.ts,package.json,package-lock.json,tsconfig.json,postcss.config.mjs,eslint.config.mjs"
          target: "/home/rgeral/docker/cv-app"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 192.168.1.22
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/rgeral/docker/cv-app
            docker-compose down --remove-orphans || true
            docker-compose build
            docker-compose up -d --remove-orphans 
