name: Deploy to NAS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard resolvconf
          echo "${{ secrets.WIREGUARD_CONFIG }}" > wg0.conf
          sudo wg-quick up ./wg0.conf
          # Attendre que la connexion soit établie
          sleep 5

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.1.22 >> ~/.ssh/known_hosts
          # Vérifier que la clé est valide
          ssh-keygen -l -f ~/.ssh/id_rsa

      - name: Copy files to NAS via SCP
        run: |
          scp -r app components data lib public types Dockerfile docker-compose.yml .dockerignore next.config.ts package.json package-lock.json tsconfig.json postcss.config.mjs eslint.config.mjs ${{ secrets.SERVER_USER }}@192.168.1.22:/home/rgeral/docker/cv-app/

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.SERVER_USER }}@192.168.1.22 << 'EOF'
            cd /home/rgeral/docker/cv-app
            docker-compose down --remove-orphans || true
            docker-compose build
            docker-compose up -d --remove-orphans
          EOF
